Update to deprecation warning
loophole@evilofallroot:~/rwhois$ ruby -e 'require "whois"; require "whois-parser"; puts Whois.whois("whois-pr.com").available?'
Traceback (most recent call last):
-e:1:in `<main>': undefined method `available?' for #<Whois::Record:0x00005616807da040> (NoMethodError)

loophole@evilofallroot:~/rwhois$ ruby -e 'require "whois"; require "whois-parser"; puts Whois.whois("whois-pr.com").parser.available?'
true